### ISSUE TITLE
Problem with certificates after 0.7.1

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [rustls/rustls-native-certs#116]
So, as I found out, I had a certificate installed for a proxy or something like that, and apparently it didn't have the correct permissions set.
```
openat(AT_FDCWD, "/usr/lib/ssl/certs/f6eee659.0", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
```
But the interesting thing is that this problem appeared only after update 0.7.1, and before that it worked fine and probably missed a bad certificate.

**Comment by djc** [comment]
Yes, we were previously ignoring the `ProbeResult::cert_dir` from openssl-probe and only started using it in this release, so I think that's expected. I guess we'll have to see if we need to ignore permission denied errors like this, depending on how often that happens. Maybe we should add some context to the errors so it's clearer what file is causing trouble?

**Comment by cpu** [comment]
> Maybe we should add some context to the errors so it's clearer what file is causing trouble?

I feel like that's a better solution than silently skipping directories or files with invalid permissions. 

Trust anchor certificates are public data and so there's no sense in having restrictive file permissions or ownership. I suspect in most cases if this happens it's by mistake and so surfacing the issue clearly feels like the right approach.

**Comment by cpu** [comment]
> surfacing the issue clearly feels like the right approach.

https://github.com/rustls/rustls-native-certs/pull/117
