### ISSUE TITLE
finding corrupted certificate on MacOS Catalina

### ISSUE THREAD

**Issue by marekyggdrasil** [rustls/rustls-native-certs#15]
Hi! First of all, I'm no rust programmer or anything, I just want a thing that depends on a thing that depends on your thing to start to work so...

There was this problem https://github.com/mimblewimble/grin-wallet/issues/554 and I traced it down to this https://github.com/ctz/hyper-rustls/blob/5a30ca520ab382bdeb06ba37a1401b6f5aeb971f/src/connector.rs#L42

I suspect it is one of my certificates that breaks it. I wanted to make something similar to what has been done here https://github.com/ctz/rustls-native-certs/issues/4#issuecomment-593443164 which is, write a code snipped that shows which certificate breaks, I just have one that reproduces the problem

```rust
use rustls_native_certs::load_native_certs;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let _dafuck = match rustls_native_certs::load_native_certs() {
        Ok(store) => store,
        Err((Some(store), err)) => {
            println!("Could not load all certificates: {:?}", err);
            store
        }
        Err((None, err)) => Err(err).expect("cannot access native cert store"),
    };
   Ok(())
}
```

is there any chance I can detect which certificate breaks it, then I can remove it / update it / whatever and world can become a happy place once again?

Thanks in advance!

**Comment by Shnatsel** [comment]
I have also received a report of the same error in my project when run in Mac OS 10.14.6: `Could not load platform certs: "The Trust Settings Record was corrupted."`

My project uses `rustls-native-certs` via `ureq`. Details here: https://github.com/rust-secure-code/cargo-supply-chain/issues/44

**Comment by Matthias247** [comment]
> is there any chance I can detect which certificate breaks it, then I can remove it / update it / whatever and world can become a happy place once again?

You can use a forked version of the library and add some extra debug printing [here](https://github.com/ctz/rustls-native-certs/blob/bf4233f31487250e91c72883743291c396854a37/src/macos.rs#L58) to figure out which cert is rejected.

**Comment by djc** [comment]
It returns a `Vec<Certificate>`, where `Certificate` is just a `Vec<u8>` newtype.

**Comment by mefellows** [comment]
Ah I see, it loads the platform specific function (not the one in lib.rs).

So I think we can resolve in reqwest directly then.
