### ISSUE TITLE
crate doc comment is incorrect and references function that doesn't exist

### ISSUE THREAD

**Issue by wfraser** [rustls/rustls-native-certs#37]
See:
https://github.com/rustls/rustls-native-certs/blob/f5b6e5bf1ea9c318d5383817f6528e306f77004c/src/lib.rs#L4-L11

`build_native_certs` is gone, and `load_native_certs` doesn't return a `RootCertStore` any more.

Consider replacing this with the snippet in the example:
```
    let mut roots = rustls::RootCertStore::empty();
    for cert in rustls_native_certs::load_native_certs().expect("could not load platform certs") {
        roots
            .add(&rustls::Certificate(cert.0))
            .unwrap();
    }
```
It was not very obvious to me how to upgrade this crate without digging into the examples to figure out how to turn a vec of certificates into a `RootCertStore`.

**Comment by djc** [comment]
Oops, thanks for the bug report. Do the changes proposed in #38 make things clearer? If you have any suggestions about how to further improve things, that would be much appreciated.

**Comment by wfraser** [comment]
Yeah, that looks great. Thanks!
