### ISSUE TITLE
Example "google" breaks with TLS introspection enabled.

### ISSUE THREAD

**Issue by jkelleyrtp** [rustls/rustls-native-certs#54]
Hi, I'm running in a corporate environment with TLS introspection enabled. Rustls just won't work at all, constantly returning `InvalidCertificateData("invalid peer certificate: UnknownIssuer")`.

Is there some flag or config to enable to allow TLS introspection?

**Comment by sfackler** [comment]
Have you loaded your MITM box's root cert into rustls's set of trusted roots?

**Comment by cpu** [comment]
I'm going to close this issue since we haven't heard back from @jkelleyrtp. If we get more information from the original poster we can reopen for further diagnostics. Thanks!
