### ISSUE TITLE
security-framework is unmaintained

### ISSUE THREAD

**Issue by aldanor** [rustls/rustls-native-certs#74]
On macOS, rustls-native-certs depends on `security-framework` which has been unmaintained for some time due to its maintainer resigning, and the repo has been archived:
- https://github.com/kornelski/rust-security-framework/commit/3337db6c7e38fa5e62905b25af3b8ca2ed501564
- https://github.com/kornelski/rust-security-framework/issues/188

Figured it's worth reporting this given that `rustls-native-certs` has a pretty large blast radius (1.5k dependent crates, 2M downloads/m).

**Comment by djc** [comment]
There is actually a team of new maintainers, and we have access to crates.io.

**Comment by cpu** [comment]
I believe https://github.com/x52dev/security-framework is the new repository.

**Comment by aldanor** [comment]
Thanks for clarifying! (It's not immediately obvious from just looking at crates.io or the original repo)
