### ISSUE TITLE
Support for native private keys

### ISSUE THREAD

**Issue by ancwrd1** [rustls/rustls-native-certs#8]
Feature request: support not only CA root certificates but also native certificate/key chains.

The rationale is that in the enterprise environments private keys are often part of the system certificate store and are marked as non-exportable, therefore not usable by rustls. This applies mostly to Windows I think.

Not sure if this request falls into the scope of this crate though or there should be something like `rustls-native-keys`.

The implementation would require then a native `Signer` logic and a way to find a matching key chain (e.g. by fingerprint, serial number or a subject pattern).

**Comment by Ralith** [comment]
I've seen this explicitly called out as something *ring* wants to support,
so that might be a good place to start.

**Comment by ancwrd1** [comment]
Issue can be closed, I have created my own project for this: `https://github.com/ancwrd1/rustls-cng`.
