### ISSUE TITLE
Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))-[xtensa-esp32s3-espidf]

### ISSUE THREAD

**Issue by blue-freedom-technologies** [rustls/rustls-native-certs#91]
I am using a [ESP32-S3](https://www.espressif.com/en/products/socs/esp32-s3) to make a call to a RPC node. 

So in theory if I install the [ESP x509 Certificate Bundle](https://docs.espressif.com/projects/esp-idf/en/v5.2.1/esp32s3/api-reference/protocols/esp_crt_bundle.html) in my ESP32-S3 board. I am able to  use the platform's native certificate store when operating as a TLS client.

But that's is not happing, Because the rustls-native-certs crate does not support the [ESP IDF](https://github.com/esp-rs/esp-idf-hal).

Is there in the future roadmap a plan to include the [ESP IDF](https://github.com/esp-rs/esp-idf-hal) in your crate?

**Comment by djc** [comment]
Maybe using webpki-roots is easier for your use case than rustls-native-certs?

Otherwise we might accept a PR to add support for your platform, though we're focusing more on the rustls-platform-verifier now (but not sure that's meaningful in the context of ESP-IDF).

**Comment by blue-freedom-technologies** [comment]
Hi @djc ,

The problem is the crate that we need to use with the ESP-IDF framework, uses only [rustls-native-certs](https://github.com/rustls/rustls-native-certs) not  [webpki-roots](https://github.com/rustls/webpki-roots). :(

By the way I understand, that right now you guys have other priorities. :(

Cheers,

**Comment by djc** [comment]
Which crate is that? Many crates support both or sometimes you can pass in a custom ClientConfig, allowing you to decide what roots to trust.

**Comment by ctz** [comment]
I'm not sure rustls is actually related to this issue; as far as I can see https://github.com/espressif/esp-idf/issues/13382 is actually using mbedtls? Could you post a self-contained example that reproduces this error?

**Comment by blue-freedom-technologies** [comment]
Hi @ctz ,

thank you for your message.

here it is [repo](https://github.com/blue-freedom-technologies/certificate-bundle)

to run the certificate-bundle app:
```text
cargo run --bin certificate-bundle --release
```

Don't forget you will get this error,
```text
ninja: error: '/certificate-bundle/target/xtensa-esp32s3-espidf/release/build/esp-idf-sys-fa8acc18369262f7/out/certs', needed by 'esp-idf/mbedtls/x509_crt_bundle', missing and no known rule to make it
  thread 'main' panicked at /.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:
```

then you need to copy manually to the correspondent path,

![image](https://github.com/rustls/rustls-native-certs/assets/142290531/8aa99747-75d0-434a-9128-4076a5a583f2)

and run again,
```text
cargo run --bin certificate-bundle --release
```

The result on my side is :
![image](https://github.com/rustls/rustls-native-certs/assets/142290531/4a589c33-a6ad-4c11-9db6-9a30bf102cc3)


If you know any other way of [loading](https://docs.rs/rustls-native-certs/latest/rustls_native_certs/fn.load_native_certs.html) root certificates from the ESP-IDF platform’s native certificate store, please share your idea.

Cheers,

**Comment by ctz** [comment]
Sorry, that is not reproducing the error in the title of this issue.

From searching github for the error message, it seems it might come from https://github.com/paritytech/jsonrpsee -- this crate has an API for choosing between native-certs and webpki-roots: https://github.com/paritytech/jsonrpsee/blob/master/client/ws-client/src/lib.rs#L147-L150

If you wish to persevere with using native certs on esp32, I suggest investigating the [VFS layers](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/storage/vfs.html) there and arranging for the certificate file you have to appear at the right place in the filesystem (see https://docs.rs/openssl-probe/0.1.5/src/openssl_probe/lib.rs.html#10-13 for the locations searched). But I think this route is a big waste of flash space compared to webpki-roots.

**Comment by djc** [comment]
Your error messages have nothing to do with this crate. Suggest you take this issue to an esp-idf specific community.

**Comment by blue-freedom-technologies** [comment]
> Sorry, that is not reproducing the error in the title of this issue.
> 
> From searching github for the error message, it seems it might come from https://github.com/paritytech/jsonrpsee -- this crate has an API for choosing between native-certs and webpki-roots: https://github.com/paritytech/jsonrpsee/blob/master/client/ws-client/src/lib.rs#L147-L150
> 
> If you wish to persevere with using native certs on esp32, I suggest investigating the [VFS layers](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/storage/vfs.html) there and arranging for the certificate file you have to appear at the right place in the filesystem (see https://docs.rs/openssl-probe/0.1.5/src/openssl_probe/lib.rs.html#10-13 for the locations searched). But I think this route is a big waste of flash space compared to webpki-roots.

Thank you for the advise,

Cheers,
